version: '3.8'

services:
    api:
      build: ./server
      ports:
        - "3000:3000"
      environment:
        - MONGO_URI=mongodb://mongo:27017/todos
      depends_on:
        - mongo
      volumes:
        - ./server:/app
      restart: always
        
    mongo:
      image: mongo:6
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      restart: always
         
volumes:
    mongo-data:

